# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('medical_support', models.BooleanField(default=False)),
                ('water_kl', models.FloatField(default=0)),
                ('sanitation_ok', models.BooleanField(default=True)),
                ('operational', models.BooleanField(default=True)),
                ('managed_by', models.CharField(blank=True, max_length=180)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to='districts.district')),
            ],
        ),
    ]
