# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('road_class', models.CharField(blank=True, max_length=50)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('status', models.CharField(choices=[('open', 'Open'), ('blocked', 'Blocked'), ('caution', 'Caution')], default='open', max_length=20)),
                ('flood_depth_cm', models.FloatField(default=0)),
                ('surface', models.CharField(blank=True, max_length=80)),
                ('connects_habitations', models.JSONField(blank=True, default=list)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roads', to='districts.district')),
            ],
        ),
    ]
