# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=80)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved')], default='unverified', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_name', models.CharField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='citizen', max_length=80)),
                ('confidence', models.FloatField(default=0.5)),
                ('authority_confirmed', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='districts.district')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
