export const ENDPOINTS = {
  dashboardSummary: '/dashboard/summary/',
  weather: (lat, lon) => `/ingestion/weather/?lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}`,
  damini: '/ingestion/damini/',
  districts: '/districts/',
  gisLayers: (districtId) => `/gis/layers/?district=${encodeURIComponent(districtId)}`,
  habitations: (districtId) => `/habitations/?district=${encodeURIComponent(districtId)}`,
  hazardEvents: (districtId) => `/hazards/events/?district=${encodeURIComponent(districtId)}`,
  redZones: (districtId) => `/hazards/red-zones/?district=${encodeURIComponent(districtId)}`,
  shelters: (districtId) => `/shelters/?district=${encodeURIComponent(districtId)}`,
  sites: (districtId) => `/sites/?district=${encodeURIComponent(districtId)}`,
  roads: (districtId) => `/roads/?district=${encodeURIComponent(districtId)}`,
  incidents: (districtId) => `/incidents/?district=${encodeURIComponent(districtId)}`,
  alerts: (districtId) => `/alerts/?district=${encodeURIComponent(districtId)}`,
  relocationSolve: '/relocation/solve/',
  reportsSituation: '/reports/situation-summary/',
  saiBriefing: (districtId) => `/sai/briefing/?district=${encodeURIComponent(districtId)}`,
  saiQuery: (q, districtId) => `/sai/query/?q=${encodeURIComponent(q)}&district=${encodeURIComponent(districtId)}`,
  login: '/auth/login/',
  refresh: '/auth/refresh/',
  me: '/auth/me/',
};