# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitations', '0001_initial'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='shortfall', max_length=20)),
                ('total_population', models.PositiveIntegerField(default=0)),
                ('assigned_population', models.PositiveIntegerField(default=0)),
                ('unassigned_population', models.PositiveIntegerField(default=0)),
                ('objective_cost', models.FloatField(default=0)),
                ('convergence_trace', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_allocated', models.PositiveIntegerField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('route_risk', models.FloatField(default=0)),
                ('blocked_route_encountered', models.BooleanField(default=False)),
                ('overflow_engaged', models.BooleanField(default=False)),
                ('source_habitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitations.habitation')),
                ('target_shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='relocation.relocationplan')),
            ],
        ),
    ]
