# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationSite',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('area_ha', models.FloatField(default=0)),
                ('hazard_safety_score', models.FloatField(default=0)),
                ('capacity_score', models.FloatField(default=0)),
                ('connectivity_score', models.FloatField(default=0)),
                ('terrain_score', models.FloatField(default=0)),
                ('livelihood_score', models.FloatField(default=0)),
                ('services_score', models.FloatField(default=0)),
                ('overall_suitability', models.FloatField(default=0)),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='districts.district')),
            ],
        ),
    ]
