# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('panchayath', models.CharField(blank=True, max_length=180)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('population', models.PositiveIntegerField(default=0)),
                ('households', models.PositiveIntegerField(default=0)),
                ('elevation_m', models.FloatField(default=0)),
                ('slope_deg', models.FloatField(default=0)),
                ('dist_river_km', models.FloatField(default=99)),
                ('drainage_index', models.FloatField(default=0)),
                ('elderly_pct', models.FloatField(default=0)),
                ('children_pct', models.FloatField(default=0)),
                ('disabled_pct', models.FloatField(default=0)),
                ('fragile_housing_pct', models.FloatField(default=0)),
                ('no_vehicle_pct', models.FloatField(default=0)),
                ('dist_hospital_km', models.FloatField(default=0)),
                ('hist_events', models.PositiveIntegerField(default=0)),
                ('hazard_score', models.FloatField(default=0)),
                ('vulnerability_score', models.FloatField(default=0)),
                ('exposure_score', models.FloatField(default=0)),
                ('priority_score', models.FloatField(default=0)),
                ('risk_band', models.CharField(default='low', max_length=20)),
                ('is_isolated', models.BooleanField(default=False)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitations', to='districts.district')),
            ],
        ),
    ]
