import { useState } from 'react';
import { UserRound, MapPin, Download, Settings, Volume2, Bell, Navigation, Globe2, Phone, Info, ShieldCheck, LogOut, ChevronRight, Sun, Moon, Trash2, Plus, X, Edit3, CheckCircle2, UsersRound, HeartPulse } from 'lucide-react';
import PageHeader from '../../components/common/PageHeader';
import { useApp } from '../../context/AppContext';
import { useNavigate } from 'react-router-dom';
import { LANGS, t } from '../../i18n';

export default function Profile(){
 const {store,updateSettings,updateProfile,setAuth,setToast,savedLocations=[],removeSavedLocation,addContact,removeContact}=useApp();
 const navigate=useNavigate(); const [section,setSection]=useState(null); const [newContact,setNewContact]=useState({name:'',phone:''});
 const [edit,setEdit]=useState({name:store.user?.name||'Citizen User',phone:(store.user?.phone||'+91 9876543210').replace('+91 ',''),dob:store.user?.dob||'',gender:store.user?.gender||'',bloodGroup:store.user?.bloodGroup||'',address:store.user?.address||'',emergencyContactName:store.user?.emergencyContactName||'',emergencyContactPhone:(store.user?.emergencyContactPhone||'').replace(/\D/g,''),emergencyContactRelation:store.user?.emergencyContactRelation||'',medicalNotes:store.user?.medicalNotes||''});
 const lang=store.settings.language; const user=store.user||{name:'Citizen User',phone:'+91 9876543210'};
 const item=(Icon,title,sub,onClick)=><button className="settings-item" onClick={onClick}><span className="setting-icon"><Icon/></span><span><b>{title}</b><small>{sub}</small></span><ChevronRight/></button>;
 const logout=()=>{setAuth(false,null);navigate('/login')};
 const add=()=>{if(!newContact.name||!/\d{10}/.test(newContact.phone)){setToast('Enter a name and valid 10-digit number.');return}addContact({id:Date.now().toString(),name:newContact.name,phone:'+91 '+newContact.phone});setNewContact({name:'',phone:''});setToast('Emergency contact added.');};
 const saveProfile=()=>{if(!edit.name.trim()||!/\d{10}/.test(edit.phone.replace(/\D/g,''))){setToast('Enter a valid name and 10-digit mobile number.');return}if(edit.emergencyContactPhone&&!/^\d{10}$/.test(edit.emergencyContactPhone.replace(/\D/g,''))){setToast('Enter a valid emergency contact number.');return}updateProfile({...edit,name:edit.name.trim(),phone:'+91 '+edit.phone.replace(/\D/g,''),emergencyContactPhone:edit.emergencyContactPhone?'+91 '+edit.emergencyContactPhone.replace(/\D/g,''):''});setToast('All profile details saved to your citizen account on this device.');setSection(null);};
 return <div className="page"><PageHeader title={t('Profile & Settings',lang)} subtitle="Manage your app preferences"/>
 <section className="profile-card"><div className="avatar">{user.name.slice(0,2).toUpperCase()}</div><div className="profile-main"><h2>{user.name}</h2><p>{user.phone}</p><span><ShieldCheck size={13}/> Citizen account</span></div><button className="profile-edit-btn" onClick={()=>{setEdit({name:user.name,phone:user.phone.replace('+91 ',''),dob:user.dob||'',gender:user.gender||'',bloodGroup:user.bloodGroup||'',address:user.address||'',emergencyContactName:user.emergencyContactName||'',emergencyContactPhone:(user.emergencyContactPhone||'').replace(/\D/g,''),emergencyContactRelation:user.emergencyContactRelation||'',medicalNotes:user.medicalNotes||''});setSection('edit')}}><Edit3/> Edit</button></section>
 <h3 className="settings-title">{t('Safety & access',lang)}</h3><div className="settings-list">
 {item(MapPin,t('Saved Locations',lang),`${savedLocations.length} places saved`,()=>setSection('saved'))}{item(Download,t('Downloaded / Offline Data',lang),'Review cached citizen-safe information',()=>navigate('/offline'))}{item(Phone,t('Emergency Contacts',lang),`${(store.emergencyContacts||[]).length} contacts configured`,()=>setSection('contacts'))}
 {item(UsersRound,'Family Safety Circle',`${(store.family?.members||[]).length} family members linked`,()=>navigate('/family'))}
 {item(Globe2,t('Language',lang),lang,()=>setSection('language'))}
 </div>
 <h3 className="settings-title">{t('App settings',lang)}</h3><div className="settings-list">
 {item(Bell,t('Notifications',lang),store.settings.notifications?'Enabled':'Disabled',()=>updateSettings({notifications:!store.settings.notifications}))}
 {item(Volume2,t('Critical voice alerts',lang),store.settings.voiceAlerts?'Enabled':'Disabled',()=>updateSettings({voiceAlerts:!store.settings.voiceAlerts}))}
 {item(Navigation,t('Navigation voice',lang),store.settings.navigationVoice?'Enabled':'Disabled',()=>updateSettings({navigationVoice:!store.settings.navigationVoice}))}
 {item(Settings,t('Location permission',lang),store.settings.location?'Enabled':'Disabled',async()=>{if(store.settings.location){updateSettings({location:false});setToast('E-Rakshan location access is now disabled. Browser permission can be changed from the site settings.');return}if(!navigator.geolocation){setToast('This browser does not support location.');return}navigator.geolocation.getCurrentPosition(()=>{updateSettings({location:true});setToast('Location permission enabled.');},()=>setToast('Location permission was not granted. Allow it in the browser and try again.'),{enableHighAccuracy:true,timeout:8000,maximumAge:0})})}
 <div className="theme-setting-row"><span className="setting-icon">{store.settings.theme==='dark'?<Moon/>:<Sun/>}</span><span><b>{store.settings.theme==='dark'?t('Dark theme',lang):t('Light theme',lang)}</b><small>{store.settings.theme==='dark'?'Dark mode is active':'Light mode is active'}</small></span><button className={`switch ${store.settings.theme==='dark'?'on':''}`} onClick={()=>updateSettings({theme:store.settings.theme==='dark'?'light':'dark'})} aria-label="Toggle dark theme"><i/></button></div>
 {item(Info,t('About E-Rakshan',lang),'Citizen App v1.0.0',()=>setSection('about'))}
 </div><button className="logout-btn" onClick={logout}><LogOut/> {t('Logout',lang)}</button>
 {section&&<div className="modal-backdrop" onClick={()=>setSection(null)}><div className="settings-modal" onClick={e=>e.stopPropagation()}><button className="icon-btn modal-close" onClick={()=>setSection(null)}><X/></button>
 {section==='edit'&&<><h2>{t('Edit profile',lang)}</h2><p>Update every citizen detail stored with your account on this device.</p><label>Full name</label><div className="auth-input"><UserRound/><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></div><div className="two-field-grid"><div><label>Date of birth</label><input className="strict-select" type="date" value={edit.dob} onChange={e=>setEdit({...edit,dob:e.target.value})}/></div><div><label>Gender</label><select className="strict-select" value={edit.gender} onChange={e=>setEdit({...edit,gender:e.target.value})}><option value="">Select</option><option>Female</option><option>Male</option><option>Other</option><option>Prefer not to say</option></select></div></div><div className="two-field-grid"><div><label>Blood group</label><select className="strict-select" value={edit.bloodGroup} onChange={e=>setEdit({...edit,bloodGroup:e.target.value})}><option value="">Unknown</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select></div><div><label>Mobile number</label><div className="auth-input"><Phone/><span>+91</span><input inputMode="numeric" maxLength="10" value={edit.phone} onChange={e=>setEdit({...edit,phone:e.target.value.replace(/\D/g,'')})}/></div></div></div><label>Current address</label><div className="auth-input"><MapPin/><input value={edit.address} onChange={e=>setEdit({...edit,address:e.target.value})} placeholder="City / district / address"/></div><div className="field-section-title emergency-field-title"><HeartPulse size={15}/><span>Emergency contact</span></div><div className="two-field-grid"><div><label>Contact name</label><div className="auth-input"><UserRound/><input value={edit.emergencyContactName} onChange={e=>setEdit({...edit,emergencyContactName:e.target.value})}/></div></div><div><label>Relation</label><select className="strict-select" value={edit.emergencyContactRelation} onChange={e=>setEdit({...edit,emergencyContactRelation:e.target.value})}><option value="">Select</option><option>Parent</option><option>Spouse</option><option>Sibling</option><option>Child</option><option>Friend</option><option>Other</option></select></div></div><label>Emergency contact number</label><div className="auth-input"><Phone/><span>+91</span><input inputMode="numeric" maxLength="10" value={edit.emergencyContactPhone} onChange={e=>setEdit({...edit,emergencyContactPhone:e.target.value.replace(/\D/g,'')})}/></div><label>Medical / accessibility notes</label><textarea className="strict-textarea" value={edit.medicalNotes} onChange={e=>setEdit({...edit,medicalNotes:e.target.value})} placeholder="Allergies, accessibility needs or essential responder information"/><div className="modal-actions"><button className="secondary-btn" onClick={()=>setSection(null)}>{t('Cancel',lang)}</button><button className="primary-btn" onClick={saveProfile}><CheckCircle2/> {t('Save changes',lang)}</button></div></>}
 {section==='language'&&<><h2>{t('Choose language',lang)}</h2><p>English is the default. Hindi and Marathi update the app interface and SAI voice.</p><div className="choice-list">{LANGS.map(x=><button className={lang===x?'chosen':''} key={x} onClick={()=>{updateSettings({language:x});setToast(`Language changed to ${x}.`);setSection(null)}}><Globe2/><span>{x}</span>{lang===x&&<span className="check-mark">✓</span>}</button>)}</div></>}
 {section==='saved'&&<><h2>{t('Saved Locations',lang)}</h2>{savedLocations.length?<div className="modal-list">{savedLocations.map(x=><div key={x.id}><MapPin/><span><b>{x.name}</b><small>{Number(x.lat).toFixed(5)}, {Number(x.lng).toFixed(5)}</small></span><button onClick={()=>removeSavedLocation(x.id)}><Trash2/></button></div>)}</div>:<p>No saved locations yet. Save a place from Live Map.</p>}</>}
 {section==='contacts'&&<><h2>{t('Emergency Contacts',lang)}</h2><div className="modal-list">{(store.emergencyContacts||[]).map(x=><div key={x.id}><Phone/><span><b>{x.name}</b><small>{x.phone}</small></span><a href={`tel:${x.phone}`} className="mini-call">Call</a><button onClick={()=>removeContact(x.id)}><Trash2/></button></div>)}</div><div className="contact-form"><input placeholder="Contact name" value={newContact.name} onChange={e=>setNewContact({...newContact,name:e.target.value})}/><input inputMode="numeric" maxLength="10" placeholder="10-digit mobile" value={newContact.phone} onChange={e=>setNewContact({...newContact,phone:e.target.value.replace(/\D/g,'')})}/><button className="primary-btn full" onClick={add}><Plus/> {t('Add contact',lang)}</button></div></>}
 {section==='about'&&<><h2>{t('About E-Rakshan',lang)}</h2><p>E-Rakshan is a citizen safety interface for alerts, hazards, shelters, navigation and offline access.</p><div className="about-points"><span>✓ Responsive citizen-first interface</span><span>✓ Online + offline architecture</span><span>✓ SAI multilingual voice assistant</span></div></>}
 </div></div>}
 </div>;
}
