# Generated by Django 5.2.17 on 2026-09-15 09:34

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_type', models.CharField(choices=[('flood', 'Flood'), ('landslide', 'Landslide'), ('cloudburst', 'Cloudburst'), ('erosion', 'Coastal erosion'), ('lightning', 'Lightning')], max_length=30)),
                ('severity', models.FloatField(default=0)),
                ('probability', models.FloatField(default=0)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('confidence', models.FloatField(default=0.5)),
                ('observed_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_events', to='districts.district')),
            ],
        ),
        migrations.CreateModel(
            name='RedZone',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('hazard_type', models.CharField(max_length=30)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('base_severity', models.FloatField(default=0)),
                ('current_severity', models.FloatField(default=0)),
                ('probability', models.FloatField(default=0)),
                ('population_exposed', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_zones', to='districts.district')),
            ],
        ),
    ]
