services:
  db:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-erakshan}
      POSTGRES_USER: ${POSTGRES_USER:-erakshan}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-erakshan}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-erakshan} -d ${POSTGRES_DB:-erakshan}"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../E-Rakshan-frontend:/e-rakshan-frontend:ro
  beat:
    build: .
    command: celery -A config beat -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app

  celery:
    build: .
    command: celery -A config worker -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
    volumes:
      - .:/app

volumes:
  postgres_data:
